import = ["/Users/shiro/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]
live_config_reload = true

[cursor]
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
# family = "IntoneMono Nerd Font Mono"
family = "LXGWWenKaiMonoTC Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "IntoneMono Nerd Font Mono"
family = "LXGWWenKaiMonoTC Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "IntoneMono Nerd Font Mono"
family = "LXGWWenKaiMonoTC Nerd Font"
style = "Italic"

[font.normal]
# family = "IntoneMono Nerd Font Mono"
family = "LXGWWenKaiMonoTC Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[window]
decorations = "transparent"
dynamic_padding = false
opacity = 0.9
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 20

[window.position]
x = 0
y = 0
